language: node_js

env:
  global:
    - ENV=ci
    - DOCKER=false

node_js:
- '10'
- '12'
- '14'

before_script:
- make install

script:
- make lint

deploy:
  provider: script
  skip_cleanup: true
  cleanup: true
  script: make publish
  on:
    tags: true
    condition: ${TRAVIS_NODE_VERSION} = 12