language: node_js

node_js:
- '10'
- '12'
- '14'

before_script:
- make install ENV=ci

script:
- make lint DOCKER=false

deploy:
  provider: npm
  email: rich2309@gmail.com
  cleanup: true
  api_key:
    secure: cZORX33EI9LZe41C5GsBzc/7LOnzE691PxPb9JtbVC51BIOAwnGkUwWM1CB4930BR6BR+p+iiCmeFroZFs75RM6pc8pvr99rEE+eGxAHZW5nOotAkhLMNxoa1fT1U9gCWEuYbRTUYFBucu8vMctLMyLJpweFbcCJCf10ynlGz/4UUYjxVWuu3l/WL9/prIOGSq6coy4lkz/81bEmKwujpF9O1DeFXhXfZk3n5Ustpwalq4y4UcOv5dOl7ShYPqDdThHYkbSUlTI1BmaPptPupgDrtDGPq9AWtEPNr0hW/ci2nPD67q25HCJ7y7aL5DS8yJvHStNpYsNzulURTRq+fjkR23N4st/SpBm/ofnACUhjTJjTVdt+M1ATXzgA71WfJOrsx36GFkfHBv2MycS33ap4QOToZeSoNtV/JEwicM0z5x0aG6zpFYRvIEZq6gToA8b7YUsWb9NWjpT2YCPjuu0RrblMtwp4XoJf1AimGG1HOkpzDXQbyV7o5smWYKdD19Bk+PSfn6en9YO1K1KSdQnGZSUkAA1KACcwJiWpA2aNLLfN1YV/26iSv6s6R0mYqzHVq7CERisncxE7otGmv7hx10ydkHmAuvQQx9REz7JwOxsIyZGn6adVtvdts78M/A2SlP41CfxKIRioOgTrwJPOHFvzLCbAdmgZ5tRYHhY=
  on:
    tags: true